### ISSUE TITLE
Setuptools 39 can't find SetuptoolsLegacyVersion

### ISSUE THREAD

**Issue by mdpiper** [csdms/model_metadata#6]
An update to setuptools caused SetuptoolsLegacyVersion to go missing.

```
>>> import setuptools
>>> setuptools.__version__
'39.0.1'
>>> from pkg_resources import parse_version, SetuptoolsLegacyVersion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name SetuptoolsLegacyVersion
```

The above worked with setuptools 38.5.1.
